githubConfigUrl: "https://github.com/keenuts-test-org/llvm-ci-testing"
githubConfigSecret: "github-token"

minRunners: 0
maxRunners: 4

containerMode:
  type: "kubernetes"
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "standard-rwo"
    resources:
      requests:
        storage: 100Gi

template:
  spec:
    tolerations:
    - key: "premerge-platform"
      operator: "Equal"
      value: "linux"
      effect: "NoSchedule"
    nodeSelector:
      premerge-platform: linux
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      resources:
        requests:
          cpu: 7
      env:
        - name: ACTIONS_RUNNER_CONTAINER_HOOKS
          value: /home/runner/k8s/index.js
        - name: ACTIONS_RUNNER_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "true"
        - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
          value: "/home/runner/pod-config/linux-container-pod-template.yaml"
      volumeMounts:
        - name: container-pod-config
          mountPath: /home/runner/pod-config
    securityContext:
      fsGroup: 123
    volumes:
      - name: container-pod-config
        configMap:
          name: linux-container-pod-template
